data = dict(
    type='PortfolioManagementDataset',
    data_path='data/portfolio_management/dj30',
    train_path='data/portfolio_management/dj30/train.csv',
    valid_path='data/portfolio_management/dj30/valid.csv',
    test_path='data/portfolio_management/dj30/test.csv',
    tech_indicator_list=[
        'zopen', 'zhigh', 'zlow', 'zadjcp', 'zclose', 'zd_5', 'zd_10', 'zd_15',
        'zd_20', 'zd_25', 'zd_30'
    ],
    length_day=10,
    initial_amount=100000,
    transaction_cost_pct=0.001,
    test_dynamic_path='data/portfolio_management/dj30/test_with_label.csv',
    test_dynamic='-1')
environment = dict(type='PortfolioManagementEIIEEnvironment')
agent = dict(
    type='PortfolioManagementEIIE',
    memory_capacity=1000,
    gamma=0.99,
    policy_update_frequency=500)
trainer = dict(
    type='PortfolioManagementEIIETrainer',
    epochs=2,
    work_dir='work_dir/portfolio_management_dj30_titans_eiie_adam_mse',
    if_remove=False)
loss = dict(type='MSELoss')
optimizer = dict(type='Adam', lr=0.0003)
titans_d_model = 128
titans_depth = 2
titans_heads = 4
titans_dim_head = 32
titans_segment_len = 32
titans_persist_mem = 4
titans_longterm_mem = 16
titans_ff_mult = 4
titans_dropout = 0.1
act = dict(
    type='TitansPortfolioActor',
    input_dim=11,
    stock_dim=29,
    time_steps=10,
    d_model=256,
    depth=4,
    heads=8,
    dim_head=32,
    segment_len=128,
    num_persist_mem_tokens=16,
    num_longterm_mem_tokens=16,
    ff_mult=4,
    output_dim=None,
    dropout=0.1)
cri = dict(
    type='TitansPortfolioCritic',
    input_dim=11,
    stock_dim=29,
    time_steps=10,
    d_model=128,
    depth=2,
    heads=4,
    dim_head=32,
    segment_len=32,
    num_persist_mem_tokens=4,
    num_longterm_mem_tokens=16,
    ff_mult=4,
    action_dim=29,
    output_dim=1,
    dropout=0.1)
transition = dict(type='Transition')
task_name = 'portfolio_management'
dataset_name = 'dj30'
net_name = 'titans'
agent_name = 'eiie'
optimizer_name = 'adam'
loss_name = 'mse'
work_dir = 'work_dir/portfolio_management_dj30_titans_eiie_adam_mse'
aact = dict(
    type='TitansPortfolioActor',
    input_dim=None,
    stock_dim=None,
    time_steps=None,
    d_model=128,
    depth=2,
    heads=4,
    dim_head=32,
    segment_len=32,
    num_persist_mem_tokens=4,
    num_longterm_mem_tokens=16,
    ff_mult=4,
    output_dim=None,
    dropout=0.1)
